/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ERC721HandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "appendData"
      | "getDataHistory"
      | "getOwner"
      | "setLotRoom"
      | "transfer"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DataAppended"): EventFragment;

  encodeFunctionData(
    functionFragment: "appendData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataHistory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setLotRoom",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "appendData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDataHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLotRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
}

export namespace DataAppendedEvent {
  export type InputTuple = [tokenId: BigNumberish, data: BytesLike];
  export type OutputTuple = [tokenId: bigint, data: string];
  export interface OutputObject {
    tokenId: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC721Handler extends BaseContract {
  connect(runner?: ContractRunner | null): ERC721Handler;
  waitForDeployment(): Promise<this>;

  interface: ERC721HandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  appendData: TypedContractMethod<[d: BytesLike], [void], "nonpayable">;

  getDataHistory: TypedContractMethod<[], [string[]], "view">;

  getOwner: TypedContractMethod<[], [string], "view">;

  setLotRoom: TypedContractMethod<[room: AddressLike], [void], "nonpayable">;

  transfer: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "appendData"
  ): TypedContractMethod<[d: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDataHistory"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setLotRoom"
  ): TypedContractMethod<[room: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DataAppended"
  ): TypedContractEvent<
    DataAppendedEvent.InputTuple,
    DataAppendedEvent.OutputTuple,
    DataAppendedEvent.OutputObject
  >;

  filters: {
    "DataAppended(uint256,bytes)": TypedContractEvent<
      DataAppendedEvent.InputTuple,
      DataAppendedEvent.OutputTuple,
      DataAppendedEvent.OutputObject
    >;
    DataAppended: TypedContractEvent<
      DataAppendedEvent.InputTuple,
      DataAppendedEvent.OutputTuple,
      DataAppendedEvent.OutputObject
    >;
  };
}
