/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { ERC721Handler } from "./ERC721Handler";
export type { LotRoom } from "./LotRoom";
