/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LotRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "blockStep"
      | "buy"
      | "deposit"
      | "downHand"
      | "ethStep"
      | "finalBlock"
      | "getFinalPrice"
      | "getLotRoomInfo"
      | "initBlock"
      | "isMember"
      | "isNFTOwner"
      | "nftHandler"
      | "owner"
      | "price"
      | "raiseHand"
      | "tokenID"
      | "updateTokenData"
      | "waitingBlocks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NFTOwnerUpdated" | "RoomUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "blockStep", values?: undefined): string;
  encodeFunctionData(functionFragment: "buy", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "downHand", values?: undefined): string;
  encodeFunctionData(functionFragment: "ethStep", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLotRoomInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initBlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNFTOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftHandler",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(functionFragment: "raiseHand", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokenID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTokenData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "waitingBlocks",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "blockStep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "downHand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ethStep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFinalPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLotRoomInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initBlock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isNFTOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nftHandler", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raiseHand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "waitingBlocks",
    data: BytesLike
  ): Result;
}

export namespace NFTOwnerUpdatedEvent {
  export type InputTuple = [newOwner: AddressLike];
  export type OutputTuple = [newOwner: string];
  export interface OutputObject {
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomUpdatedEvent {
  export type InputTuple = [roomLength: BigNumberish];
  export type OutputTuple = [roomLength: bigint];
  export interface OutputObject {
    roomLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LotRoom extends BaseContract {
  connect(runner?: ContractRunner | null): LotRoom;
  waitForDeployment(): Promise<this>;

  interface: LotRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blockStep: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<[], [void], "payable">;

  deposit: TypedContractMethod<[], [bigint], "view">;

  downHand: TypedContractMethod<[], [void], "nonpayable">;

  ethStep: TypedContractMethod<[], [bigint], "view">;

  finalBlock: TypedContractMethod<[], [bigint], "view">;

  getFinalPrice: TypedContractMethod<[], [bigint], "view">;

  getLotRoomInfo: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        _tokenID: bigint;
        _initBlock: bigint;
        _currentPrice: bigint;
        _deposit: bigint;
        _ethStep: bigint;
        _waitingBlocks: bigint;
        _blockStep: bigint;
        _memberCount: bigint;
        _isWaiting: boolean;
      }
    ],
    "view"
  >;

  initBlock: TypedContractMethod<[], [bigint], "view">;

  isMember: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isNFTOwner: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  nftHandler: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  price: TypedContractMethod<[], [bigint], "view">;

  raiseHand: TypedContractMethod<[], [void], "payable">;

  tokenID: TypedContractMethod<[], [bigint], "view">;

  updateTokenData: TypedContractMethod<
    [newData: BytesLike],
    [void],
    "nonpayable"
  >;

  waitingBlocks: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blockStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "downHand"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFinalPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLotRoomInfo"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        _tokenID: bigint;
        _initBlock: bigint;
        _currentPrice: bigint;
        _deposit: bigint;
        _ethStep: bigint;
        _waitingBlocks: bigint;
        _blockStep: bigint;
        _memberCount: bigint;
        _isWaiting: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNFTOwner"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nftHandler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseHand"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "tokenID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateTokenData"
  ): TypedContractMethod<[newData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "waitingBlocks"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "NFTOwnerUpdated"
  ): TypedContractEvent<
    NFTOwnerUpdatedEvent.InputTuple,
    NFTOwnerUpdatedEvent.OutputTuple,
    NFTOwnerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomUpdated"
  ): TypedContractEvent<
    RoomUpdatedEvent.InputTuple,
    RoomUpdatedEvent.OutputTuple,
    RoomUpdatedEvent.OutputObject
  >;

  filters: {
    "NFTOwnerUpdated(address)": TypedContractEvent<
      NFTOwnerUpdatedEvent.InputTuple,
      NFTOwnerUpdatedEvent.OutputTuple,
      NFTOwnerUpdatedEvent.OutputObject
    >;
    NFTOwnerUpdated: TypedContractEvent<
      NFTOwnerUpdatedEvent.InputTuple,
      NFTOwnerUpdatedEvent.OutputTuple,
      NFTOwnerUpdatedEvent.OutputObject
    >;

    "RoomUpdated(uint256)": TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
    RoomUpdated: TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
  };
}
