/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LotRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bStep"
      | "buy"
      | "dep"
      | "downHand"
      | "finalB"
      | "getPrice"
      | "h"
      | "id"
      | "info"
      | "initB"
      | "owner"
      | "raiseHand"
      | "start"
      | "step"
      | "update"
      | "waitB"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "O" | "R"): EventFragment;

  encodeFunctionData(functionFragment: "bStep", values?: undefined): string;
  encodeFunctionData(functionFragment: "buy", values?: undefined): string;
  encodeFunctionData(functionFragment: "dep", values?: undefined): string;
  encodeFunctionData(functionFragment: "downHand", values?: undefined): string;
  encodeFunctionData(functionFragment: "finalB", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "h", values?: undefined): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "info", values?: undefined): string;
  encodeFunctionData(functionFragment: "initB", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "raiseHand", values?: undefined): string;
  encodeFunctionData(functionFragment: "start", values?: undefined): string;
  encodeFunctionData(functionFragment: "step", values?: undefined): string;
  encodeFunctionData(functionFragment: "update", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "waitB", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bStep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dep", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "downHand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "h", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "info", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raiseHand", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "step", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "waitB", data: BytesLike): Result;
}

export namespace OEvent {
  export type InputTuple = [arg0: AddressLike];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace REvent {
  export type InputTuple = [arg0: BigNumberish];
  export type OutputTuple = [arg0: bigint];
  export interface OutputObject {
    arg0: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LotRoom extends BaseContract {
  connect(runner?: ContractRunner | null): LotRoom;
  waitForDeployment(): Promise<this>;

  interface: LotRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bStep: TypedContractMethod<[], [bigint], "view">;

  buy: TypedContractMethod<[], [void], "payable">;

  dep: TypedContractMethod<[], [bigint], "view">;

  downHand: TypedContractMethod<[], [void], "nonpayable">;

  finalB: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  h: TypedContractMethod<[], [string], "view">;

  id: TypedContractMethod<[], [bigint], "view">;

  info: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        string[]
      ] & {
        _id: bigint;
        _initB: bigint;
        _price: bigint;
        _dep: bigint;
        _step: bigint;
        _waitB: bigint;
        _bStep: bigint;
        _count: bigint;
        _isWait: boolean;
        _isMember: boolean;
        _isOwner: boolean;
        _h: string[];
      }
    ],
    "view"
  >;

  initB: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseHand: TypedContractMethod<[], [void], "payable">;

  start: TypedContractMethod<[], [bigint], "view">;

  step: TypedContractMethod<[], [bigint], "view">;

  update: TypedContractMethod<[data: BytesLike], [void], "nonpayable">;

  waitB: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "dep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "downHand"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "h"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "id"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "info"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        string[]
      ] & {
        _id: bigint;
        _initB: bigint;
        _price: bigint;
        _dep: bigint;
        _step: bigint;
        _waitB: bigint;
        _bStep: bigint;
        _count: bigint;
        _isWait: boolean;
        _isMember: boolean;
        _isOwner: boolean;
        _h: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseHand"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "start"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "step"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "update"
  ): TypedContractMethod<[data: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "waitB"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "O"
  ): TypedContractEvent<
    OEvent.InputTuple,
    OEvent.OutputTuple,
    OEvent.OutputObject
  >;
  getEvent(
    key: "R"
  ): TypedContractEvent<
    REvent.InputTuple,
    REvent.OutputTuple,
    REvent.OutputObject
  >;

  filters: {
    "O(address)": TypedContractEvent<
      OEvent.InputTuple,
      OEvent.OutputTuple,
      OEvent.OutputObject
    >;
    O: TypedContractEvent<
      OEvent.InputTuple,
      OEvent.OutputTuple,
      OEvent.OutputObject
    >;

    "R(uint256)": TypedContractEvent<
      REvent.InputTuple,
      REvent.OutputTuple,
      REvent.OutputObject
    >;
    R: TypedContractEvent<
      REvent.InputTuple,
      REvent.OutputTuple,
      REvent.OutputObject
    >;
  };
}
