/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LotRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "downHand"
      | "getCountOfMembers"
      | "getFinalPrice"
      | "getStaticInfo"
      | "isMember"
      | "isNFTOwner"
      | "isWaiting"
      | "owner"
      | "raiseHand"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NFTOwnerUpdated" | "RoomUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "buy", values?: undefined): string;
  encodeFunctionData(functionFragment: "downHand", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCountOfMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFinalPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStaticInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isMember", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isNFTOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isWaiting", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "raiseHand", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "downHand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountOfMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFinalPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStaticInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isNFTOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isWaiting", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raiseHand", data: BytesLike): Result;
}

export namespace NFTOwnerUpdatedEvent {
  export type InputTuple = [_owner: AddressLike];
  export type OutputTuple = [_owner: string];
  export interface OutputObject {
    _owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomUpdatedEvent {
  export type InputTuple = [roomLength: BigNumberish];
  export type OutputTuple = [roomLength: bigint];
  export interface OutputObject {
    roomLength: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LotRoom extends BaseContract {
  connect(runner?: ContractRunner | null): LotRoom;
  waitForDeployment(): Promise<this>;

  interface: LotRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<[], [void], "payable">;

  downHand: TypedContractMethod<[], [void], "payable">;

  getCountOfMembers: TypedContractMethod<[], [bigint], "view">;

  getFinalPrice: TypedContractMethod<[], [bigint], "view">;

  getStaticInfo: TypedContractMethod<
    [],
    [[bigint, bigint, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;

  isMember: TypedContractMethod<[], [boolean], "view">;

  isNFTOwner: TypedContractMethod<[], [boolean], "view">;

  isWaiting: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  raiseHand: TypedContractMethod<[], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "downHand"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getCountOfMembers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFinalPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStaticInfo"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint, bigint, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isNFTOwner"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWaiting"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseHand"
  ): TypedContractMethod<[], [void], "payable">;

  getEvent(
    key: "NFTOwnerUpdated"
  ): TypedContractEvent<
    NFTOwnerUpdatedEvent.InputTuple,
    NFTOwnerUpdatedEvent.OutputTuple,
    NFTOwnerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomUpdated"
  ): TypedContractEvent<
    RoomUpdatedEvent.InputTuple,
    RoomUpdatedEvent.OutputTuple,
    RoomUpdatedEvent.OutputObject
  >;

  filters: {
    "NFTOwnerUpdated(address)": TypedContractEvent<
      NFTOwnerUpdatedEvent.InputTuple,
      NFTOwnerUpdatedEvent.OutputTuple,
      NFTOwnerUpdatedEvent.OutputObject
    >;
    NFTOwnerUpdated: TypedContractEvent<
      NFTOwnerUpdatedEvent.InputTuple,
      NFTOwnerUpdatedEvent.OutputTuple,
      NFTOwnerUpdatedEvent.OutputObject
    >;

    "RoomUpdated(uint256)": TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
    RoomUpdated: TypedContractEvent<
      RoomUpdatedEvent.InputTuple,
      RoomUpdatedEvent.OutputTuple,
      RoomUpdatedEvent.OutputObject
    >;
  };
}
