/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RoomHandlerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "doesExist"
      | "getCountOfMembers"
      | "getDepositFromAddress"
      | "push"
      | "remove"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "doesExist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCountOfMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositFromAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "push",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "remove", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "doesExist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCountOfMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositFromAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "push", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remove", data: BytesLike): Result;
}

export interface RoomHandler extends BaseContract {
  connect(runner?: ContractRunner | null): RoomHandler;
  waitForDeployment(): Promise<this>;

  interface: RoomHandlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doesExist: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  getCountOfMembers: TypedContractMethod<[], [bigint], "view">;

  getDepositFromAddress: TypedContractMethod<
    [addr: AddressLike],
    [bigint],
    "view"
  >;

  push: TypedContractMethod<
    [addr: AddressLike, deposit: BigNumberish],
    [void],
    "nonpayable"
  >;

  remove: TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doesExist"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCountOfMembers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDepositFromAddress"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "push"
  ): TypedContractMethod<
    [addr: AddressLike, deposit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remove"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;

  filters: {};
}
