name: linting, testing, building
on:
  push:
    branches:
      - master
      - loki-fixes
  pull_request:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ matrix.node-version }}
      - name: install modules
        run: yarn install --frozen-lockfile
      - name: build project
        run: yarn build:prod
#      - name: linting typescript
#        run: yarn lint
#      - name: linting scss
#        run: yarn styleLint-check
#      - name: unit testing
#        run: yarn test-unit
      - name: screenshot testing
        run: yarn test-ui:ci
        continue-on-error: true
      - name: Archive screenshots to artifact
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: screenshots
          path: .loki/*
          retention-days: 1